#pragma once
#ifndef PRJ_VERSION_H
#define PRJ_VERSION_H

#define PRJ_VER_MAJOR 1
#define PRJ_VER_MINOR 0
#define PRJ_VER_PATCH 0

#define PRJ_VERSION (PRJ_VER_MAJOR * 10000 + PRJ_VER_MINOR * 100 + PRJ_VER_PATCH)

#endif // !PRJ_VERSION_H
